<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>Glyph.Assets.Domain</RootNamespace>
    <AssemblyName>Glyph.Assets.Domain</AssemblyName>
  </PropertyGroup>

</Project>
