<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b30b2176-2e3e-4287-9130-c7034da52182</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\contracts\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\..\..\shared\web\Shared.Web\Shared.Web.csproj" />
    <ProjectReference Include="..\Glyph.Assets.Application\Glyph.Assets.Application.csproj" />
    <ProjectReference Include="..\Glyph.Assets.Infrastructure\Glyph.Assets.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Glyph.Assets.Api</RootNamespace>
    <AssemblyName>Glyph.Assets.Api</AssemblyName>
  </PropertyGroup>

</Project>
