<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Crossdyne.Toolkit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\Glyph.Domain\Glyph.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Glyph.Application</RootNamespace>
    <AssemblyName>Glyph.Application</AssemblyName>
  </PropertyGroup>

</Project>
